### ISSUE TITLE
Embed output change

### ISSUE THREAD

**Issue by jalpp** [jalpp/LichessSearchEngineBot#16]
change the output of /profile, /dailypuzzlecc, /puzzle into embed forms

**Comment by susmitha1103** [comment]
Hey, I would like to work on this. Can I work on this?

**Comment by jalpp** [comment]
sure please do, I will assign it to you, if you need help, feel free to join dev community server which is in README, thanks!

**Comment by jalpp** [comment]
how is it going? @susmitha1103 need any help here?

**Comment by jalpp** [comment]
f612f8365e7b2db1fa9f1801e9e0d2a015ef5ee6 fixes this
